name: Publish container image

on:
  workflow_dispatch:
  release:
    types:
    - created
  schedule:
  - cron: 00 00 * * 0

permissions:
  contents: read

jobs:
  docker:
    permissions:
      # for docker/build-push-action to publish docker image
      packages: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1  # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set tag for image
      env:
        REF_TYPE: ${{ github.ref_type }}
        REF_NAME: ${{ github.ref_name }}
      run: >-
        echo IMAGE_TAG=$(
        [ $REF_TYPE == 'tag' ]
        && echo $REF_NAME
        || echo 'latest'
        ) >> $GITHUB_ENV

    - name: Set IMAGE_REPO environment variable
      # Lowercase the org/repo name to allow for workflow to run in forks,
      # which owners have uppercase letters in username
      run: >-
        echo "IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1

    - name: Build and Push release
      if: github.event_name != 'schedule'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: .
        build-args: |
          INSTALL_ALL=true
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE_REPO }}:latest
        # Fix multi-platform: https://github.com/docker/buildx/issues/1533
        provenance: false
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Build and Push tools release
      if: github.event_name != 'schedule'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: .
        file: ./Dockerfile.tools
        build-args: |
          BASE_IMAGE=${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_REPO }}-tools:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE_REPO }}-tools:latest
        # Fix multi-platform: https://github.com/docker/buildx/issues/1533
        provenance: false
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Test tools image
      if: github.event_name != 'schedule'
      env:
        IMAGE_TAG: ${{ env.IMAGE_REPO }}-tools:${{ env.IMAGE_TAG }}
      run: |
        echo "Testing tools image: $IMAGE_TAG"
        docker run --rm "$IMAGE_TAG" terraform --version
        docker run --rm "$IMAGE_TAG" terraform-docs --version
        docker run --rm "$IMAGE_TAG" tflint --version
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Build and Push nightly
      if: github.event_name == 'schedule'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: .
        build-args: |
          INSTALL_ALL=true
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_REPO }}:nightly
        # Fix multi-platform: https://github.com/docker/buildx/issues/1533
        provenance: false
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Build and Push tools nightly
      if: github.event_name == 'schedule'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: .
        file: ./Dockerfile.tools
        build-args: |
          BASE_IMAGE=${{ env.IMAGE_REPO }}:nightly
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_REPO }}-tools:nightly
        # Fix multi-platform: https://github.com/docker/buildx/issues/1533
        provenance: false
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"
