name: Build and Publish Docker Tools Image

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-tools

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false

    - name: Log in to Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: .
        file: ./Dockerfile.tools
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Extract first image tag
      id: extract_tag
      run: |
        echo "tag=$(echo '${{ steps.meta.outputs.tags }}' | head -n1)" >> $GITHUB_OUTPUT

    - name: Test Docker image
      run: |
        echo "Testing image: ${{ steps.extract_tag.outputs.tag }}"
        docker run --rm ${{ steps.extract_tag.outputs.tag }} terraform --version
        docker run --rm ${{ steps.extract_tag.outputs.tag }} terraform-docs --version
        docker run --rm ${{ steps.extract_tag.outputs.tag }} tflint --version
